export const enum EVENTLOCATION {
  HALL_2 = 'HALL_2',

  HALL_3 = 'HALL_3',

  GALLERY_UPSTAIRS = 'GALLERY_UPSTAIRS',

  MAIN_HALL = 'MAIN_HALL',

  HOME = 'HOME',

  GNSG_SENIOR_CENTER = 'GNSG_SENIOR_CENTER',
}
