export const enum EVENTTYPE {
  SUKHMANI_SAHIB = 'SUKHMANI_SAHIB',

  SUKHMANI_SAHIB_AT_HOME = 'SUKHMANI_SAHIB_AT_HOME',

  FUNERAL_SEHAJ_PATH_BHOG = 'FUNERAL_SEHAJ_PATH_BHOG',

  AKHAND_PATH_SAHIB = 'AKHAND_PATH_SAHIB',

  SEHAJ_PATH_START = 'SEHAJ_PATH_START',

  LANGAR = 'LANGAR',

  KIRTAN = 'KIRTAN',

  SEHAJ_PATH_BHOG = 'SEHAJ_PATH_BHOG',

  DEG_SEVA = 'DEG_SEVA',
}
