package org.gnsg.gms.domain.enumeration;

/**
 * The EVENTTYPE enumeration.
 */
public enum EVENTTYPE {
    SUKHMANI_SAHIB, SUKHMANI_SAHIB_AT_HOME, FUNERAL_SEHAJ_PATH_BHOG, AKHAND_PATH_SAHIB, SEHAJ_PATH_START, LANGAR, KIRTAN, SEHAJ_PATH_BHOG, DEG_SEVA
}
